/* auto-generated by fix-core-types.js */
export interface RouteOptions {
  rate_limit_limit?: number | null
  rate_limit_window?: number | null
  cache_ttl?: number | null
  jwt_auth?: boolean | null
}

export class NativeEngine {
  constructor(port: number)
  registerRoute(method: string, path: string, handlerId: number, options?: RouteOptions | null): void
  registerStaticRoute(method: string, path: string, content: string, contentType: string, options?: RouteOptions | null): void
  registerJsonRoute(method: string, path: string, content: string, options?: RouteOptions | null): void
  registerUploadRoute(method: string, path: string, dir: string, handlerId?: number | null, options?: RouteOptions | null): void
  addStaticRoute(prefix: string, dir: string): void
  setHandler(callback: (event: { handlerId: number, reqId: string, params: string[], query: string, headers: string[], method: string, url: string, body: Buffer, responseHandle: any }) => void): void
  setWsHandler(callback: (event: { socketId: string, eventType: string, payload?: string }) => void): void
  wsSend(socketId: string, message: string): void
  wsSubscribe(socketId: string, room: string): void
  wsUnsubscribe(socketId: string, room: string): void
  wsPublish(room: string, message: string): void
  setCors(origin: string, methods: String, headers: string, credentials: boolean): void
  setSecurityHeaders(enabled: boolean): void
  setTls(certPath: string, keyPath: string): void
  sendResponse(handle: any, status: number, body: string): void
  sendJson(handle: any, status: number, body: any): void
  sendHtml(handle: any, status: number, body: string): void
  connectPostgres(url: string): Promise<void>
  connectSqlite(url: string): Promise<void>
  connectRedis(url: string): void
  connectMongo(url: string): Promise<void>
  redisSet(key: string, value: string, ttl?: number | null): Promise<void>
  redisGet(key: string): Promise<string | null>
  queryDb(sql: string, ttl?: number | null): Promise<string>
  queryDbWithParams(sql: string, params: any[], ttl?: number | null): Promise<string>
  queryMongo(dbName: string, collName: string, query: string): Promise<string>
  setJwtSecret(secret: string): void
  initLogger(): void
  getMetrics(): string
  stop(): Promise<void>
  start(): Promise<void>
}
